name: TSItem
main: hu.Pdani.TSItem.TSItemPlugin
version: '1.2.2'
description: 'Custom item creator for TheServer.wtf'
api-version: '1.16'
authors: [Pdani001]
website: 'www.pdani.hu'
softdepend: [TSMenu]
permissions:
  tsitem.admin:
    default: op
    description: Permission to access the TSItem command
commands:
  tsitem:
    description: TSItem main command
    usage: '/<command> [args]'